services:
  ollama:
    image: ollama/ollama:latest
    container_name: gemma3-ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
